### PR TITLE
Upload the hexbin plot json file

### PR DESCRIPTION
**Pull request by danich1**
As mentioned in the engineering channel here is the json file for the hexbin plot. This file contains the center of each hexagon bin, the bin count and the cell number attached to each bin. You won't need to use the cell number, but I'll need it for the other json files ( the hexbin-PC associations,  journal metadata/composition for each hexbin). 

This plot was generated using [R's hexbin module](https://www.rdocumentation.org/packages/hexbin/versions/1.29.0/topics/hexbin). Let me know what else you may need to generate this plot.

### CODE REVIEW

**Comment by vincerubinetti** [comment]
This looks good to me. I was thinking all of the data would be combined into one json file, like the components/associations/etc, but if it's easier to split them up that's fine too.

Is it too big to put into one? Did you envision the frontend loading a specific smaller json file each time the user hovers over a hex cell for more details? One benefit to having all the data in one json file, if possible, would be that we could possibly make a cleverer display of the information, like having the frontend color the cells based on categories (compositions?) the user selects.

**Comment by danich1** [comment]
> I was thinking all of the data would be combined into one json file, like the components/associations/etc, but if it's easier to split them up that's fine too.
>
> Is it too big to put into one? Did you envision the frontend loading a specific smaller json file each time the user hovers over a hex cell for more details? 

I doubt it will be too big. You caught me flatfooted a sI didnt have a chance to calculate everything yet.  I wanted to give you a chance to work on getting the hexbin plot up first before I incorporated the other information; however, it makes more sense to have everything all at once. I'll let you know when I get everything together.

**Comment by vincerubinetti** [comment]
Oh that's fine too, if it's not all ready yet. I can still work with this in the meantime.

**Comment by danich1** [comment]
Cool will merge now and open a new PR will the full json later.

**Pull request merged**
