### PR TITLE
Updated SAUCIE to provide reproducable results and change the PMC landscape

### PR DESCRIPTION
**Pull request by danich1**
This pull request changes the SAUCIE model and updates the PMC landscape. The previous image that was used for the recommendation system was nor reproducible. Reason for that is tensorflow is a difficult package to deal with and certain seeds were not set. I have fixed issue and a PR for the annorxiver will be uploaded eventually (tangential to this PR).

If you need the json file to be reformatted let me know.

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Do me a favor and run `filter-plot.html` in `/frontend/public/data`. Open it in a web browser, load the `plot-full.json` and it'll save a filtered/reduced plot to replace `plot.json`.

**Comment by vincerubinetti** [comment]
Also if the bin size happened to change from `0.4`, please update this line:
https://github.com/greenelab/annorxiver-journal-recommender/blob/master/frontend/src/map.js#L16

**Comment by vincerubinetti** [comment]
If it's not too much trouble, can you also remove `, to string with comma` from this line:
https://github.com/greenelab/annorxiver-journal-recommender/blob/master/frontend/public/data/filter-plot.html#L16

That was a mistake of mine

**Review by vincerubinetti — APPROVED** [review]

**Comment by vincerubinetti** [comment]
Just to make sure, the coordinates returned for the preprint should still match the new coordinates/bin size of this updated plot?

**Comment by danich1** [comment]
Yeah I updated the saucie model to reflect the new mapping coordinates. Should be implemented now if I did everything correctly.

**Pull request merged**
