### PR TITLE
Updated the About Tool Blurb

### PR DESCRIPTION
**Pull request by danich1**
This PR updated the about tool blurb for users to read. Take a look and let me know what you think.

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Fixing these linting errors is much easier with Prettier and ESLint's autofix features. Let me format it for you.

**Comment by vincerubinetti** [comment]
[about.zip](https://github.com/greenelab/annorxiver-journal-recommender/files/5159125/about.zip)

**Comment by vincerubinetti** [comment]
[about.zip](https://github.com/greenelab/annorxiver-journal-recommender/files/5159130/about.zip)

**Comment by vincerubinetti** [comment]
Sorry, I accidentally uploaded the wrong file the first time and quickly deleted the comment. Try the same new comment.

**Comment by danich1** [comment]
Can you reload the second file? My computer keeps saying the zip is empty 😕 .

**Comment by vincerubinetti** [comment]
[about.zip](https://github.com/greenelab/annorxiver-journal-recommender/files/5159138/about.zip)

**Pull request merged**
