### PR TITLE
add basic tooltip to heatmap

### PR DESCRIPTION
**Pull request by vincerubinetti**
- add prettier config for formatting
- reformat code
- add basic tooltip functionality
- show basic cell info in tooltip
- fit heatmap to svg automatically instead of manually
- add `journal_neighbors.document` as fallback until field is renamed to `pmcid`

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Oh I thought the new plot data was already uploaded in a previous PR. Take a look at the deploy preview. More bins than before... and now it forms a circle too, which I thought was odd...

**Comment by danich1** [comment]
>Oh I thought the new plot data was already uploaded in a previous PR. Take a look at the deploy preview. More bins than before... and now it forms a circle too, which I thought was odd...

Yeah that's because I sent you data without tuning the model. The **correct** visualization is coming shortly. Also, any doi I put into the demo gives me back a cant get results error. Is it just me or am I missing something?

**Comment by vincerubinetti** [comment]
Looks like somethings wrong with the backend?

https://api-journal-rec.greenelab.com/doi/10.1101/833400

**Comment by danich1** [comment]
>Looks like somethings wrong with the backend? 

Biorxiv api is down again... Makes sense now.

**Comment by vincerubinetti** [comment]
> > Oh I thought the new plot data was already uploaded in a previous PR. Take a look at the deploy preview. More bins than before... and now it forms a circle too, which I thought was odd...
> 
> Yeah that's because I sent you data without tuning the model. The **correct** visualization is coming shortly. Also, any doi I put into the demo gives me back a cant get results error. Is it just me or am I missing something?

You can put the new data in this pr or the next. It should work automatically with the new data, assuming no field names in the json changed.

**Comment by danich1** [comment]
>You can put the new data in this pr or the next. It should work automatically with the new data, assuming no field names in the json changed.

The new data is in #25. I asssigned it to @dongbohu, but if you like to approve feel free. No code is in that PR.

**Comment by vincerubinetti** [comment]
#25 looks good to me. Shall I merge this one first?

**Comment by danich1** [comment]
Go for it!

**Pull request merged**
