### PR TITLE
Square plot of PMC journal landscape

### PR DESCRIPTION
**Pull request by danich1**
@vincerubinetti 

Here is a PR that contains the square plot for the PMC landscape. Each square has a count for the number of journal articles contained in the given bin. I also have a listing of PCs each bin is associated with as well as the association score. (can be negative). Furthermore, I've added the journal "make up" of each square bin. Now the visualization should be complete. Let me know if there is anything else you need me to add. 

Should I merge #14 first before adding this? 

Side Note: I have word cloud plots for PCs that we can add once this visualization is up and running.

### CODE REVIEW

**Comment by vincerubinetti** [comment]
image

**Comment by vincerubinetti** [comment]
Also I can just add the json data to my pr #14 if you want to just close this one. If you update the data, just throw it in a comment here (I think you can zip the json file then just drag it onto a comment).

**Comment by danich1** [comment]
>Data formatting looks good, but it looks a little underwhelming with only 7x7 bins. Could we do more?

Will look into add more.

> Also I can just add the json data to my pr #14 if you want to just close this one. If you update the data, just throw it in a comment here (I think you can zip the json file then just drag it onto a comment)

Gotcha. I'll upload the new json file as a comment in #14 and close this one.

**Comment by vincerubinetti** [comment]
I assume more bins == finer granularity == more specifics == more useful to user. Maybe 20x20? I think that's what the hex plot had.

**Pull request closed without merging**
