### PR TITLE
add basic results and messages functionality

### PR DESCRIPTION
**Pull request by vincerubinetti**
image

image

@danich1

### CODE REVIEW

**Comment by danich1** [comment]
Looking good so far! Do note that the output for the papers will have a distance measure associated with them as well (a floating point number).

**Comment by vincerubinetti** [comment]
Yes, though I've made the numbers in the circle 1 thru 10, if you hover over them you can see the exact distance score. I did this because I thought people wouldn't really care or get any meaning out of the actual distance, and they would just care which had the best score.

I also made the intensity of the orange color match the intensity of the float distance value, so for example if 1 and 2 are way more close than 3-9, they'll be way more orange and the user will be able to see that.

Does that work for you?

**Comment by danich1** [comment]
Yeah that makes sense. I like the subtlety behind hiding the distance within a mouseover.
Now that you mention it. I'm not sure the intensity of 1 and 2 but can we increase it or add more saturation to make the distinction a bit more clear.  I didn't notice that until you mentioned something.  Other than that looks great to me!

**Comment by vincerubinetti** [comment]
Yeah we can tweak the colors and range and such. It might not be a saturated enough orange but that's easy to change later.

If you're good with it for now, you can merge so you can see it in action. Right now it just uses an embedded test json response, so what's typed into the search box wont do anything different.

**Comment by danich1** [comment]
Sounds good merging now!

**Pull request merged**
