### PR TITLE
Updated word odds ratio to remove parse errors

### PR DESCRIPTION
**Pull request by danich1**
This PR updates the word-odd ratios for each bin in the PMC plot. Increased the number of words to 20 so hopefully that shouldn't break anything. I also ran your filter on the plot-fill.json file, so you shouldn't have to do anything if I did it correctly. Github says 2 additions and 2 deletions, but I verified these are the correct files. I guess the json files keep everything on the same line which would explain the reporting of me making a small change in spite of me actually making large changes.

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Looks like this broke the lemma graph. Did any of the field names in the json change?

**Comment by danich1** [comment]
>Looks like this broke the lemma graph. Did any of the field names in the json change?

No field changes unless the "bin_odds" field was suppose to be something else. I increased the array to contain 20 items instead of 15. Did that cause the issue?

**Comment by vincerubinetti** [comment]
The new `plot.json` doesn't have any `lemma` fields.

I ran this PR's `plot-full.json` through `filter-plot.html`, and here is the result:

[plot.zip](https://github.com/greenelab/annorxiver-journal-recommender/files/5261845/plot.zip)

**Comment by vincerubinetti** [comment]
Also I just realized i left in a debug message here:

https://github.com/greenelab/annorxiver-journal-recommender/blob/4143451417c3cef019b0820e8119bdf0b1989325/frontend/src/hooks.js#L9

Can you remove it for me?

**Comment by vincerubinetti** [comment]
In that last commit, `plot-full.json` and `plot.json` are now the same file, the `lemmas` field has been changed to `lemma` somehow, and the `console.log` statement doesn't show up in the diff.

**Comment by vincerubinetti** [comment]
Also do we need to show all 20 lemmas to the user, or can we just do a top ten, like we're limiting the journals to top 5. This would save space in the `plot.json` and make the user have to load less before the map can appear.

**Comment by danich1** [comment]
>In that last commit, plot-full.json and plot.json are now the same file, the lemmas field has been changed to lemma somehow, and the console.log statement doesn't show up in the diff.

Right I was using your formatting code on the pmc_square_bin.json file I had. Is it lemma or lemmas? 

>Also do we need to show all 20 lemmas to the user, or can we just do a top ten, like we're limiting the journals to top 5. This would save space in the plot.json and make the user have to load less before the map can appear.

I'll change it to top ten instead of top twenty.

**Comment by vincerubinetti** [comment]
The frontend expects it to be `lemmas`... but I'm saying that your `plot-full.json`, the data you're providing me from your end, is not the same as it was. The structure of the data has changed. Something is wrong. Can you just upload the raw data from your software (I guess `pmc_square_bin.json`?) to this thread and I'll make the changes.

**Comment by danich1** [comment]
>The frontend expects it to be lemmas... but I'm saying that your plot-full.json, the data you're providing me from your end, is not the same as it was. The structure of the data has changed. Something is wrong. Can you just upload the raw data from your software (I guess pmc_square_bin.json?) to this thread and I'll make the changes.

I figured the issue I believe. This updated commit should fix the issue. If not I'll upload my file and let you change it.

**Comment by vincerubinetti** [comment]
That commit fixed it.

Perhaps we should rename `plot-full.json` to `pmc_square_bin.json` to avoid confusion in the future? `filter-plot.html` is supposed to make it so you don't have to do any processing; so that you can just use the raw json exported from your ggplot (or whatever) software.

I'm not sure if you have a python script that's processing and exporting the full data, or if you're exporting the data directly from a third-party software. If it's the latter, maybe the proper place to limit lemmas to top 10 is in `filter-plot.html`, because that's where I'm limiting journals to top 5 too.

**Comment by danich1** [comment]
>Perhaps we should rename plot-full.json to pmc_square_bin.json to avoid confusion in the future?

That should make things easier, so we should do that. I'll make the changes on this end.

>I'm not sure if you have a python script that's processing and exporting the full data, or if you're exporting the data directly from a third-party software. If it's the latter, maybe the proper place to limit lemmas to top 10 is in filter-plot.html, because that's where I'm limiting journals to top 5 too.

Data is being exported from my own script. So I'll let the number of lemmas be 20 and then let the `filter-plot.html` handle the preprocessing.

**Comment by danich1** [comment]
At this point I renamed the plot-full file and we can leave the lemma filtering to another PR.

**Review by vincerubinetti — APPROVED** [review]

**Pull request merged**
