### PR TITLE
add basic, bare-bones frontend

### PR DESCRIPTION
**Pull request by vincerubinetti**
image

### CODE REVIEW

**Comment by vincerubinetti** [comment]
@danich1 should we move everything that's not the frontend into a folder called `server` or something, to keep the root of the repo clean?

I'd move the frontend to its own folder too, but then we'd need some CI to move it out to the root of a different branch for `gh-pages`. Keeping the frontend stuff in the root, all you have to do is go into the repo settings and set gh-pages to just read from the master root, and then "deploying" the frontend is as simple as just merging changes into master.

**Comment by danich1** [comment]
@vincerubinetti That works for me. You could also move this into your own repository if that makes it easier for you. Now that I have a better grasp of the situation it might make sense to separate the two. My bad for not seeing it earlier.

**Comment by vincerubinetti** [comment]
I was going to oblige with the idea to separate them, but now I'm thinking we should just keep it as one repo for the user's sake. I think it makes sense to have them separate for a much bigger and complicated app like Adage, but for here, I think it's nice to have a one stop shop.

**Comment by danich1** [comment]
Sounds good I'll move my code into the server folder. Then I'll set up some CI for the front end.

**Comment by vincerubinetti** [comment]
Oh I just did it in this pr just now. Take a look at the readme as well.

**Comment by vincerubinetti** [comment]
@danich1 I have nothing else to add for this PR, I guess. I figured we'll do it in some smaller chunks. You can merge whenever ready.

**Pull request merged**
